language: python
python: '3.5'

stages:
  - deploy

env:
  global:
  - COMMIT_AUTHOR_NAME: ITSLanguage Bot
  - COMMIT_AUTHOR_EMAIL: its-bot@itslanguage.nl
  - SITE_DIR: $TRAVIS_BUILD_DIR/.site 

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

after_success:
  # Failing will "fail" the build
  # doing this step in before_deploy
  # will not.
  - mkdocs build -d $SITE_DIR
  # Make sure our script is executable
  - chmod +x $TRAVIS_BUILD_DIR/gh-pages.sh

deploy:
  # Deploy to GitHub pages with our Bot user.
  # Runs when a tag is made available.
  - provider: script
    skip_cleanup: true
    script: "$TRAVIS_BUILD_DIR/gh-pages.sh"
    on:
      branch: master
      tags: true

  # Deploy to GitHub pages with our Bot user.
  # It seems that it is not possible to specify both "on"
  # arguments. Runs when master get's an update.
  - provider: script
    skip_cleanup: true
    script: "$TRAVIS_BUILD_DIR/gh-pages.sh"
    on:
      branch: master

notifications:
  slack:
    secure: h2/webRUw7XjVCWPma3ck+CJKMr5/0jj2A4zsk+Xm83dR8FOSiubWZP6I/0w6GapwcAWfAKPzLbZgPA0RHK5lOUqXyEMqJjeD6Srw1acZ7Ir0lnkC2/77+925Azhc7ZdqR2gZGvtMQ18UZ1u9St4+Gq6PGbZiJ+WY3QM8+U/OPjqpVcdcaQG1EuQrkKZyafTMeEO0zwkBnOyW0rzFKwN2kT8aGfXKvd814cvJv+H9FO0k/YZPDXxmS7nRdcnF8Hbg7x09nBa9Y9Q9vTNhBcmclUAqAbNcghD2hEYOPkRKm5hIOyzDt66vhCvDKZD3zHH/opp1sh2ClOB5Cqh7cc3MiUS/PAyAqaO+++1bfmv09SvHIydWI1jRyrxPJxtinA7WLjedkY2g7l+3cJ+WcwGgOLW+5IlSMbjTQI92TPv6aeWw/DzyAzjRGEP25Q7hFSmq2mZjCrTcI+Bm5ZZuIlvemClri4MT8rJsPSbuMzgare1TMM1WZK8oybTPkCHwDscg+hn6ZvoVWScxk/4E1dt1P0qAkXVoCyWRu/k6P4QWjtX/U6q72L6l22yZJ7D7YZOA4VKLP/JynM9CUVfrP3EG8IbG8zibeYsQn4ocIa66p9ReRu8ADjmzbbSFCKW+W01q006HE1MvmeEhvO18Z9Dwow6fvf2yrzLid5stKMcukY=

